
.PHONY: Creating topics needed for app
consumer_read_test_topic:
	kafka-console-consumer.sh --bootstrap-server eprupetw10aa:30903,eprupetw10aa:30448, eprupetw10aa:30805  --topic test-topic --from-beginning --property print.key=true